# Generated by Django 2.2.6 on 2019-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_user', models.CharField(max_length=255)),
                ('feedback_description', models.CharField(max_length=1000)),
                ('feedback_item', models.CharField(max_length=300)),
                ('feedback_date', models.CharField(max_length=10)),
            ],
        ),
    ]
