# Generated by Django 2.2.6 on 2019-10-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='feedback_date',
            field=models.DateTimeField(),
        ),
    ]
